/*
 * 216. Word Ladder
 * Topic: Graphs | Difficulty: Hard
 *
 * Find the length of the shortest transformation sequence from beginWord to
 * endWord, changing one letter at a time, where every intermediate word must be
 * in the dictionary.
 *
 * Approach: BFS over an implicit graph whose vertices are words and whose edges
 * join words differing in one letter. Neighbours are generated by substituting
 * each of the 26 letters at each position rather than by comparing all word
 * pairs, and words are erased from the dictionary once queued to avoid revisits.
 *
 * Time: O(N * L * 26) for N words of length L   Space: O(N * L)
 */
#include <bits/stdc++.h>
using namespace std;

int ladderLength(const string& beginWord, const string& endWord,
                 const vector<string>& wordList) {
    unordered_set<string> dict(wordList.begin(), wordList.end());
    if (!dict.count(endWord)) return 0;

    queue<string> q;
    q.push(beginWord);
    dict.erase(beginWord);
    int steps = 1;
    while (!q.empty()) {
        int levelSize = q.size();
        for (int i = 0; i < levelSize; ++i) {
            string word = q.front();
            q.pop();
            if (word == endWord) return steps;
            for (int pos = 0; pos < (int)word.size(); ++pos) {
                char original = word[pos];
                for (char c = 'a'; c <= 'z'; ++c) {
                    word[pos] = c;
                    if (dict.count(word)) { dict.erase(word); q.push(word); }
                }
                word[pos] = original;
            }
        }
        ++steps;
    }
    return 0;
}

int main() {
    cout << ladderLength("hit", "cog", {"hot", "dot", "dog", "lot", "log", "cog"}) << "\n";  // 5
    cout << ladderLength("hit", "cog", {"hot", "dot", "dog", "lot", "log"}) << "\n";         // 0
    return 0;
}
